import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bcc7de",
        "surface-container": "#1a211d",
        "tertiary-container": "#fc7c78",
        "on-tertiary-container": "#711419",
        "outline-variant": "#3c4a42",
        "surface-variant": "#2f3632",
        "surface-bright": "#343b36",
        "tertiary": "#ffb3af",
        "on-primary-container": "#00422b",
        "surface-dim": "#0e1511",
        "surface-container-lowest": "#09100c",
        "background": "#0e1511",
        "primary-container": "#10b981",
        "tertiary-fixed": "#ffdad7",
        "on-secondary": "#263143",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed": "#d8e3fb",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2b322d",
        "on-primary": "#003824",
        "surface-tint": "#4edea3",
        "secondary": "#bcc7de",
        "on-primary-fixed": "#002113",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary": "#650911",
        "on-background": "#dde4dd",
        "outline": "#86948a",
        "on-primary-fixed-variant": "#005236",
        "inverse-surface": "#dde4dd",
        "surface-container-highest": "#2f3632",
        "on-secondary-container": "#aeb9d0",
        "surface": "#0e1511",
        "error-container": "#93000a",
        "primary": "#4edea3",
        "surface-container-low": "#161d19",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "surface-container-high": "#242c27",
        "on-tertiary-fixed-variant": "#842225",
        "on-surface": "#dde4dd",
        "on-surface-variant": "#bbcabf",
        "on-tertiary-fixed": "#410005",
        "secondary-container": "#3e495d",
        "inverse-primary": "#006c49",
        "primary-fixed-dim": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#111c2d",
        "obsidian": "#0f172a",
        "dark-steel": "#1e293b",
        "neon-emerald": "#10b981",
        "micro-border": "#334155",
        "crimson": "#e11d48",
        "amber": "#f59e0b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "8px",
        "lg": "24px",
        "container-max": "1440px",
        "xs": "4px",
        "gutter": "16px",
        "md": "16px",
        "xl": "40px",
        "unit": "4px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-data": ["12px", { lineHeight: "18px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
};
export default config;
